version: '3.8'

services:
  neurotrack-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: neurotrack-backend:dev
    container_name: neurotrack-backend-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/neurotrack"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - neurotrack-network-dev

  postgres:
    image: postgres:16-alpine
    container_name: neurotrack-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: neurotrack
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - neurotrack-network-dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  neurotrack-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_URL=http://localhost:8080/api
    image: neurotrack-frontend:dev
    container_name: neurotrack-frontend-dev
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - neurotrack-network-dev

networks:
  neurotrack-network-dev:
    driver: bridge

volumes:
  postgres_data_dev:
